/* Subroutines used for expanding RISC-V builtins.
   Copyright (C) 2011-2020 Free Software Foundation, Inc.
   Contributed by Andrew Waterman (andrew@sifive.com).

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#define IN_TARGET_CODE 1

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "rtl.h"
#include "tree.h"
#include "gimple-expr.h"
#include "memmodel.h"
#include "expmed.h"
#include "profile-count.h"
#include "optabs.h"
#include "recog.h"
#include "diagnostic-core.h"
#include "stor-layout.h"
#include "expr.h"
#include "langhooks.h"
#include "function.h"
#include "emit-rtl.h"
#include "explow.h"

/* Macros to create an enumeration identifier for a function prototype.  */
#define RISCV_FTYPE_NAME0(A) RISCV_##A##_FTYPE
#define RISCV_FTYPE_NAME1(A, B) RISCV_##A##_FTYPE_##B
#define RISCV_FTYPE_NAME2(A, B, C) RISCV_##A##_FTYPE_##B##_##C
#define RISCV_FTYPE_NAME3(A, B, C, D) RISCV_##A##_FTYPE_##B##_##C##_##D
#define RISCV_FTYPE_NAME4(A, B, C, D, E) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E
#define RISCV_FTYPE_NAME5(A, B, C, D, E, F) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F
#define RISCV_FTYPE_NAME6(A, B, C, D, E, F, G) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F##_##G
#define RISCV_FTYPE_NAME7(A, B, C, D, E, F, G, H) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F##_##G##_##H

/* Classifies the prototype of a built-in function.  */
enum riscv_function_type {
#define DEF_RISCV_FTYPE(NARGS, LIST) RISCV_FTYPE_NAME##NARGS LIST,
#include "config/riscv/riscv-ftypes.def"
#undef DEF_RISCV_FTYPE
  RISCV_MAX_FTYPE_MAX
};

/* Specifies how a built-in function should be converted into rtl.  */
enum riscv_builtin_type {
  /* The function corresponds directly to an .md pattern.  */
  RISCV_BUILTIN_DIRECT,

  /* Likewise, but with return type VOID.  */
  RISCV_BUILTIN_DIRECT_NO_TARGET
};

/* Declare an availability predicate for built-in functions.  */
#define AVAIL(NAME, COND)		\
 static unsigned int			\
 riscv_builtin_avail_##NAME (void)	\
 {					\
   return (COND);			\
 }

/* This structure describes a single built-in function.  */
struct riscv_builtin_description {
  /* The code of the main .md file instruction.  See riscv_builtin_type
     for more information.  */
  enum insn_code icode;

  /* The name of the built-in function.  */
  const char *name;

  /* Specifies how the function should be expanded.  */
  enum riscv_builtin_type builtin_type;

  /* The function's prototype.  */
  enum riscv_function_type prototype;

  /* Whether the function is available.  */
  unsigned int (*avail) (void);
};

AVAIL (hard_float, TARGET_HARD_FLOAT)
AVAIL (zprv64, TARGET_ZPRV)
AVAIL (zpsf32, TARGET_ZPSF)
AVAIL (zpn, TARGET_ZPN)
AVAIL (zpn64, TARGET_ZPN && TARGET_64BIT)
AVAIL (zpn32, TARGET_ZPN && !TARGET_64BIT)

/* Construct a riscv_builtin_description from the given arguments.

   INSN is the name of the associated instruction pattern, without the
   leading CODE_FOR_riscv_.

   NAME is the name of the function itself, without the leading
   "__builtin_riscv_".

   BUILTIN_TYPE and FUNCTION_TYPE are riscv_builtin_description fields.

   AVAIL is the name of the availability predicate, without the leading
   riscv_builtin_avail_.  */
#define RISCV_BUILTIN(INSN, NAME, BUILTIN_TYPE,	FUNCTION_TYPE, AVAIL)	\
  { CODE_FOR_riscv_ ## INSN, "__builtin_riscv_" NAME,			\
    BUILTIN_TYPE, FUNCTION_TYPE, riscv_builtin_avail_ ## AVAIL }

/* Define __builtin_riscv_<INSN>, which is a RISCV_BUILTIN_DIRECT function
   mapped to instruction CODE_FOR_riscv_<INSN>,  FUNCTION_TYPE and AVAIL
   are as for RISCV_BUILTIN.  */
#define DIRECT_BUILTIN(INSN, FUNCTION_TYPE, AVAIL)			\
  RISCV_BUILTIN (INSN, #INSN, RISCV_BUILTIN_DIRECT, FUNCTION_TYPE, AVAIL)

/* Define __builtin_riscv_<INSN>, which is a RISCV_BUILTIN_DIRECT_NO_TARGET
   function mapped to instruction CODE_FOR_riscv_<INSN>,  FUNCTION_TYPE
   and AVAIL are as for RISCV_BUILTIN.  */
#define DIRECT_NO_TARGET_BUILTIN(INSN, FUNCTION_TYPE, AVAIL)		\
  RISCV_BUILTIN (INSN, #INSN, RISCV_BUILTIN_DIRECT_NO_TARGET,		\
		FUNCTION_TYPE, AVAIL)

#define RVP_RISCV_BUILTIN(INSN, NAME,	FUNCTION_TYPE, AVAIL)	\
  { CODE_FOR_ ## INSN, "__builtin_riscv_" NAME,			\
    RISCV_BUILTIN_DIRECT, FUNCTION_TYPE, riscv_builtin_avail_ ## AVAIL }

#define RVP_RISCV_BUILTIN(INSN, NAME,	BUILTIN_TYPE, FUNCTION_TYPE, AVAIL)	\
  { CODE_FOR_ ## INSN, "__builtin_riscv_" NAME,			\
    BUILTIN_TYPE, FUNCTION_TYPE, riscv_builtin_avail_ ## AVAIL }

#define RVP_NO_TARGET_BUILTIN(ICODE, INSN, FUNCTION_TYPE, AVAIL)			\
  RVP_RISCV_BUILTIN (ICODE, #INSN, RISCV_BUILTIN_DIRECT_NO_TARGET, FUNCTION_TYPE, AVAIL)

#define RVP_DIRECT_BUILTIN(ICODE, INSN, FUNCTION_TYPE, AVAIL)			\
  RVP_RISCV_BUILTIN (ICODE, #INSN, RISCV_BUILTIN_DIRECT, FUNCTION_TYPE, AVAIL)

/* Helper type node for target-specific types support 
   [FIXME] if you find a better way to define insn patterns with 
   arguments intxlen_t */
tree uint_xlen_node;
tree int_xlen_node;

/* Argument types.  */
#define RISCV_ATYPE_VOID void_type_node
#define RISCV_ATYPE_SI intSI_type_node
#define RISCV_ATYPE_USI unsigned_intSI_type_node
#define RISCV_ATYPE_ULONG long_unsigned_type_node
#define RISCV_ATYPE_LONG long_integer_type_node
#define RISCV_ATYPE_LLONG long_long_integer_type_node
#define RISCV_ATYPE_ULLONG  long_long_unsigned_type_node
#define RISCV_ATYPE_PSI build_pointer_type (integer_type_node)
#define RISCV_ATYPE_PUSI build_pointer_type (unsigned_type_node)
#define RISCV_ATYPE_PLLONG build_pointer_type (long_long_integer_type_node)
#define RISCV_ATYPE_PULLONG build_pointer_type (long_long_unsigned_type_node)
#define RISCV_ATYPE_TI intTI_type_node
#define RISCV_ATYPE_UTI unsigned_intTI_type_node
#define RISCV_ATYPE_V4QI build_vector_type (intQI_type_node, 4)
#define RISCV_ATYPE_UV4QI build_vector_type (unsigned_intQI_type_node, 4)
#define RISCV_ATYPE_V8QI build_vector_type (intQI_type_node, 8)
#define RISCV_ATYPE_UV8QI build_vector_type (unsigned_intQI_type_node, 8)
#define RISCV_ATYPE_V2HI build_vector_type (intHI_type_node, 2)
#define RISCV_ATYPE_UV2HI build_vector_type (unsigned_intHI_type_node, 2)
#define RISCV_ATYPE_V4HI build_vector_type (intHI_type_node, 4)
#define RISCV_ATYPE_UV4HI build_vector_type (unsigned_intHI_type_node, 4)
#define RISCV_ATYPE_V2SI build_vector_type (intSI_type_node, 2)
#define RISCV_ATYPE_UV2SI build_vector_type (unsigned_intSI_type_node, 2)
#define RISCV_ATYPE_V4SI build_vector_type (intSI_type_node, 4)
#define RISCV_ATYPE_UV4SI build_vector_type (unsigned_intSI_type_node, 4)
#define RISCV_ATYPE_V8HI build_vector_type (intHI_type_node, 8)
#define RISCV_ATYPE_UV8HI build_vector_type (unsigned_intHI_type_node, 8)

#define RISCV_ATYPE_DI intDI_type_node
#define RISCV_ATYPE_UDI unsigned_intDI_type_node
#define RISCV_ATYPE_IXLEN  int_xlen_node
#define RISCV_ATYPE_UIXLEN uint_xlen_node

/* RISCV_FTYPE_ATYPESN takes N RISCV_FTYPES-like type codes and lists
   their associated RISCV_ATYPEs.  */
#define RISCV_FTYPE_ATYPES0(A) \
  RISCV_ATYPE_##A
#define RISCV_FTYPE_ATYPES1(A, B) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B
#define RISCV_FTYPE_ATYPES2(A, B, C) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C
#define RISCV_FTYPE_ATYPES3(A, B, C, D) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D
#define RISCV_FTYPE_ATYPES4(A, B, C, D, E) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E
#define RISCV_FTYPE_ATYPES5(A, B, C, D, E, F) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F
#define RISCV_FTYPE_ATYPES6(A, B, C, D, E, F, G) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F, RISCV_ATYPE_##G
#define RISCV_FTYPE_ATYPES7(A, B, C, D, E, F, G, H) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F, RISCV_ATYPE_##G, RISCV_ATYPE_##H

static const struct riscv_builtin_description riscv_builtins[] = {
  RVP_DIRECT_BUILTIN (addv2hi3, add16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (addv4hi3, add16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (raddv2hi3, radd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (raddv4hi3, radd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uraddv2hi3, uradd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uraddv4hi3, uradd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kaddv2hi3, kadd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kaddv4hi3, kadd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukaddv2hi3, ukadd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukaddv4hi3, ukadd16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (subv2hi3, sub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (subv4hi3, sub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rsubv2hi3, rsub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rsubv4hi3, rsub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ursubv2hi3, ursub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ursubv4hi3, ursub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ksubv2hi3, ksub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ksubv4hi3, ksub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uksubv2hi3, uksub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uksubv4hi3, uksub16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (crasv2hi, cras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (cras16_64, cras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rcrasv2hi, rcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rcras16_64, rcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (urcrasv2hi, urcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (urcras16_64, urcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kcrasv2hi, kcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kcras16_64, kcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukcrasv2hi, ukcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukcras16_64, ukcras16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (crsav2hi, crsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (crsa16_64, crsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rcrsav2hi, rcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rcrsa16_64, rcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (urcrsav2hi, urcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (urcrsa16_64, urcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kcrsav2hi, kcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kcrsa16_64, kcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukcrsav2hi, ukcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukcrsa16_64, ukcrsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (stasv2hi, stas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (stas16_64, stas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rstasv2hi, rstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rstas16_64, rstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (urstasv2hi, urstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (urstas16_64, urstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kstasv2hi, kstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kstas16_64, kstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukstasv2hi, ukstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukstas16_64, ukstas16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (stsav2hi, stsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (stsa16_64, stsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rstsav2hi, rstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rstsa16_64, rstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (urstsav2hi, urstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (urstsa16_64, urstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kstsav2hi, kstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kstsa16_64, kstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukstsav2hi, ukstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukstsa16_64, ukstsa16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (addv4qi3, add8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (addv8qi3, add8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (raddv4qi3, radd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (raddv8qi3, radd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uraddv4qi3, uradd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uraddv8qi3, uradd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ukaddv4qi3, ukadd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ukaddv8qi3, ukadd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (subv4qi3, sub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (subv8qi3, sub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (rsubv4qi3, rsub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (rsubv8qi3, rsub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ursubv4qi3, ursub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ursubv8qi3, ursub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ksubv4qi3, ksub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ksubv8qi3, ksub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uksubv4qi3, uksub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uksubv8qi3, uksub8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ashrv2hi3, sra16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ashrv4hi3, sra16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sra16_roundv2hi, sra16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sra16_roundv4hi, sra16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (lshrv2hi3, srl16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (lshrv4hi3, srl16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (srl16_roundv2hi, srl16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (srl16_roundv4hi, srl16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ashlv2hi3, sll16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ashlv4hi3, sll16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslli16v2hi, ksll16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kslli16v4hi, ksll16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslrav2hisi, kslra16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kslrav4hidi, kslra16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslrav2hisi_round, kslra16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kslrav4hidi_round, kslra16_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ashrv4qi3, sra8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ashrv8qi3, sra8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sra8_roundv4qi, sra8_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sra8_roundv8qi, sra8_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (lshrv4qi3, srl8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (lshrv8qi3, srl8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (srl8_roundv4qi, srl8_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (srl8_roundv8qi, srl8_u, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ashlv4qi3, sll8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ashlv8qi3, sll8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslli8v4qisi, ksll8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kslli8v8qidi, ksll8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslrav4qisi, kslra8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kslrav8qidi, kslra8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kslrav4qisi_round, kslra8_u, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zpn32),
  RVP_DIRECT_BUILTIN (kslrav8qidi_round, kslra8_u, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zpn64),
  RVP_DIRECT_BUILTIN (cmpeqv2hi, cmpeq16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (cmpeqv4hi, cmpeq16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (scmpltv2hi, scmplt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (scmpltv4hi, scmplt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (scmplev2hi, scmple16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (scmplev4hi, scmple16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ucmpltv2hi, ucmplt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ucmpltv4hi, ucmplt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ucmplev2hi, ucmple16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ucmplev4hi, ucmple16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (cmpeqv4qi, cmpeq8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (cmpeqv8qi, cmpeq8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (scmpltv4qi, scmplt8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (scmpltv8qi, scmplt8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (scmplev4qi, scmple8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (scmplev8qi, scmple8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ucmpltv4qi, ucmplt8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ucmpltv8qi, ucmplt8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (ucmplev4qi, ucmple8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (ucmplev8qi, ucmple8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smul16, smul16, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (smulx16, smulx16, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (umul16, umul16, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (umulx16, umulx16, RISCV_ULLONG_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (umulx16_64, umulx16, RISCV_ULLONG_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (khm16v2hi, khm16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (khm16v4hi, khm16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (khmx16v2hi, khmx16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (khmx16v4hi, khmx16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smul8, smul8, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (smulx8, smulx8, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (umul8, umul8, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (umulx8, umulx8, RISCV_ULLONG_FTYPE_USI_USI, zpsf32),
  RVP_DIRECT_BUILTIN (khm8v4qi, khm8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (khm8v8qi, khm8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (khmx8v4qi, khmx8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (khmx8v8qi, khmx8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sminv2hi3, smin16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sminv4hi3, smin16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uminv2hi3, umin16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uminv4hi3, umin16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smaxv2hi3, smax16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smaxv4hi3, smax16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (umaxv2hi3, umax16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (umaxv4hi3, umax16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sclip16v2hi, sclip16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sclip16v4hi, sclip16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uclip16v2hi, uclip16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uclip16v4hi, uclip16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kabsv2hi2, kabs16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kabsv4hi2, kabs16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clrsbv2hi2, clrs16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clrsbv4hi2, clrs16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clzv2hi2, clz16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clzv4hi2, clz16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clov2hi2, clo16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clov4hi2, clo16, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sminv4qi3, smin8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sminv8qi3, smin8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uminv4qi3, umin8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uminv8qi3, umin8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smaxv4qi3, smax8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smaxv8qi3, smax8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (umaxv4qi3, umax8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (umaxv8qi3, umax8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kabsv4qi2, kabs8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kabsv8qi2, kabs8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sclip8v4qi, sclip8, RISCV_IXLEN_FTYPE_IXLEN_USI, zpn32),
  RVP_DIRECT_BUILTIN (sclip8v8qi, sclip8, RISCV_IXLEN_FTYPE_IXLEN_USI, zpn64),
  RVP_DIRECT_BUILTIN (uclip8v4qi, uclip8, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zpn32),
  RVP_DIRECT_BUILTIN (uclip8v8qi, uclip8, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zpn64),
  RVP_DIRECT_BUILTIN (clrsbv4qi2, clrs8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clrsbv8qi2, clrs8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clzv4qi2, clz8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clzv8qi2, clz8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clov4qi2, clo8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clov8qi2, clo8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (unspec_bswap8, swap8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (unspec_bswap8_64, swap8, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sunpkd810, sunpkd810, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sunpkd810_64, sunpkd810, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sunpkd820, sunpkd820, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sunpkd820_64, sunpkd820, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sunpkd830, sunpkd830, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sunpkd830_64, sunpkd830, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sunpkd831, sunpkd831, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sunpkd831_64, sunpkd831, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sunpkd832, sunpkd832, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sunpkd832_64, sunpkd832, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (zunpkd810, zunpkd810, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (zunpkd810_64, zunpkd810, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (zunpkd820, zunpkd820, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (zunpkd820_64, zunpkd820, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (zunpkd830, zunpkd830, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (zunpkd830_64, zunpkd830, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (zunpkd831, zunpkd831, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (zunpkd831_64, zunpkd831, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (zunpkd832, zunpkd832, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (zunpkd832_64, zunpkd832, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pkbbv2hi, pkbb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pkbb64, pkbb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pkbtv2hi, pkbt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pkbt64, pkbt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pktbv2hi, pktb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pktb64, pktb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pkttv2hi, pktt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pktt64, pktt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smulsi3_highpart, smmul, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smulv2si3_highpart, smmul, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smmul_round, smmul_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smmulv2si3_round, smmul_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmac, kmmac, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmac_64, kmmac, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmac_round, kmmac_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmac64_round, kmmac_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmsb, kmmsb, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmsb_64, kmmsb, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmsb_round, kmmsb_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmsb64_round, kmmsb_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kwmmul, kwmmul, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kwmmul_64, kwmmul, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kwmmul_round, kwmmul_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kwmmul64_round, kwmmul_u, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smmwb, smmwb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smmwb64, smmwb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smmwb_round, smmwb_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smmwb64_round, smmwb_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smmwt, smmwt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smmwt64, smmwt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smmwt_round, smmwt_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smmwt64_round, smmwt_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawb, kmmawb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawb64, kmmawb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawb_round, kmmawb_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawb64_round, kmmawb_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawt, kmmawt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawt64, kmmawt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawt_round, kmmawt_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawt64_round, kmmawt_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmwb2, kmmwb2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmwb64, kmmwb2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmwb2_round, kmmwb2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmwb64_round, kmmwb2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmwt2, kmmwt2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmwt64, kmmwt2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmwt2_round, kmmwt2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmwt64_round, kmmwt2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawb2, kmmawb2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawb2_64, kmmawb2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawb2_round, kmmawb2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawb2_64_round, kmmawb2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawt2, kmmawt2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawt2_64, kmmawt2, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmmawt2_round, kmmawt2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmmawt2_64_round, kmmawt2_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smbb, smbb16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smbb64, smbb16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smbt, smbt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smbt64, smbt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smtt, smtt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smtt64, smtt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmda, kmda, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmda64, kmda, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmxda, kmxda, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmxda64, kmxda, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smds, smds, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smds64, smds, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smdrs, smdrs, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smdrs64, smdrs, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smxdsv, smxds, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smxds64, smxds, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmabb, kmabb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmabb64, kmabb, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmabt, kmabt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmabt64, kmabt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmatt, kmatt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmatt64, kmatt, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmada, kmada, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmada64, kmada, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmaxda, kmaxda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmaxda64, kmaxda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmads, kmads, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmads64, kmads, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmadrs, kmadrs, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmadrs64, kmadrs, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmaxds, kmaxds, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmaxds64, kmaxds, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmsda, kmsda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmsda64, kmsda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kmsxda, kmsxda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kmsxda64, kmsxda, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smal1, smal, RISCV_LLONG_FTYPE_LLONG_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (sclip32sisi, sclip32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sclip32v2sidi, sclip32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (uclip32sisi, uclip32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (uclip32v2sidi, uclip32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clrsbsi2, clrs32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clrsbv2si2, clrs32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (clzsi2, clz32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clzv2si2, clz32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (closi2, clo32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (clov2si2, clo32, RISCV_UIXLEN_FTYPE_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pbsadsi, pbsad, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pbsaddi, pbsad, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (pbsadasi, pbsada, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (pbsadadi, pbsada, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smaqa, smaqa, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smaqa64, smaqa, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (umaqa, umaqa, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (umaqa64, umaqa, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sumaqa, smaqa_su, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sumaqa64, smaqa_su, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (radddi3, radd64, RISCV_LLONG_FTYPE_LLONG_LLONG, zpsf32),
  RVP_DIRECT_BUILTIN (uradddi3, uradd64, RISCV_ULLONG_FTYPE_ULLONG_ULLONG, zpsf32),
  RVP_DIRECT_BUILTIN (dsp_kadddi3, kadd64, RISCV_LLONG_FTYPE_LLONG_LLONG, zpsf32),
  RVP_DIRECT_BUILTIN (dsp_ukadddi3, ukadd64, RISCV_ULLONG_FTYPE_ULLONG_ULLONG, zprv64),
  RVP_DIRECT_BUILTIN (rsubdi3, rsub64, RISCV_LLONG_FTYPE_LLONG_LLONG, zpsf32),
  RVP_DIRECT_BUILTIN (ursubdi3, ursub64, RISCV_ULLONG_FTYPE_ULLONG_ULLONG, zpsf32),
  RVP_DIRECT_BUILTIN (dsp_ksubdi3, ksub64, RISCV_LLONG_FTYPE_LLONG_LLONG, zpsf32),
  RVP_DIRECT_BUILTIN (dsp_uksubdi3, uksub64, RISCV_ULLONG_FTYPE_ULLONG_ULLONG, zpsf32),
  RVP_DIRECT_BUILTIN (smar64_1, smar64, RISCV_LLONG_FTYPE_LLONG_IXLEN_IXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smsr64, smsr64, RISCV_LLONG_FTYPE_LLONG_IXLEN_IXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (umar64_1, umar64, RISCV_ULLONG_FTYPE_ULLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (umsr64, umsr64, RISCV_ULLONG_FTYPE_ULLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (kmar64_1, kmar64, RISCV_LLONG_FTYPE_LLONG_IXLEN_IXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (kmsr64, kmsr64, RISCV_LLONG_FTYPE_LLONG_IXLEN_IXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (ukmar64_1, ukmar64, RISCV_ULLONG_FTYPE_ULLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (ukmsr64, ukmsr64, RISCV_ULLONG_FTYPE_ULLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalbb, smalbb, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalbt, smalbt, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smaltt, smaltt, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalda1, smalda, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalxda1, smalxda, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalds1, smalds, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smaldrs3, smaldrs, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smalxds1, smalxds, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (smslda1, smslda, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (smslda64, smslda, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (smslxda1, smslxda, RISCV_LLONG_FTYPE_LLONG_UIXLEN_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (kaddh, kaddh, RISCV_IXLEN_FTYPE_SI_SI, zpn),
  RVP_DIRECT_BUILTIN (ksubh, ksubh, RISCV_IXLEN_FTYPE_SI_SI, zpn),
  RVP_DIRECT_BUILTIN (khmbbv2hi, khmbb, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (khmbb64, khmbb, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (khmbtv2hi, khmbt, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (khmbt64, khmbt, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (khmttv2hi, khmtt, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (khmtt64, khmtt, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (ukaddh, ukaddh, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (ukaddh64, ukaddh, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (uksubh, uksubh, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (uksubh64, uksubh, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kaddw, kaddw, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (kaddw64, kaddw, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (ukaddw, ukaddw, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (ukaddw64, ukaddw, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (ksubw, ksubw, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (ksubw64, ksubw, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (uksubw, uksubw, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (uksubw64, uksubw, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kdmbbv2hi, kdmbb, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmbb64, kdmbb, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kdmbtv2hi, kdmbt, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmbt64, kdmbt, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kdmttv2hi, kdmtt, RISCV_IXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmtt64, kdmtt, RISCV_IXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kslraw, kslraw, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (kslraw64, kslraw, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (unspec_kslrawu, kslraw_u, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (unspec_kslrawu64, kslraw_u, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (kssl, ksllw, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn),
  RVP_DIRECT_BUILTIN (kdmabb, kdmabb, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmabb32, kdmabb, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kdmabt, kdmabt, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmabt32, kdmabt, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kdmatt, kdmatt, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (kdmatt32, kdmatt, RISCV_IXLEN_FTYPE_IXLEN_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (kabs, kabsw, RISCV_UIXLEN_FTYPE_IXLEN, zpn),
  RVP_DIRECT_BUILTIN (raddsi3, raddw, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (radddisi3, raddw, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (uraddsi3, uraddw, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (uradddisi3, uraddw, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (rsubsi3, rsubw, RISCV_IXLEN_FTYPE_SI_SI, zpn32),
  RVP_DIRECT_BUILTIN (rsubdisi3, rsubw, RISCV_IXLEN_FTYPE_SI_SI, zpn64),
  RVP_DIRECT_BUILTIN (ursubsi3, ursubw, RISCV_UIXLEN_FTYPE_USI_USI, zpn32),
  RVP_DIRECT_BUILTIN (ursubdisi3, ursubw, RISCV_UIXLEN_FTYPE_USI_USI, zpn64),
  RVP_DIRECT_BUILTIN (smaxsi3, maxw, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn),
  RVP_DIRECT_BUILTIN (sminsi3, minw, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn),
  RVP_DIRECT_BUILTIN (unspec_ave, ave, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn32),
  RVP_DIRECT_BUILTIN (unspec_avedi, ave, RISCV_IXLEN_FTYPE_IXLEN_IXLEN, zpn64),
  RVP_DIRECT_BUILTIN (sraiu, sra_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (sraiu64, sra_u, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (bitrev, bitrev, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (bitrev64, bitrev, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (wext, wext, RISCV_UIXLEN_FTYPE_LLONG_UIXLEN, zpsf32),
  RVP_DIRECT_BUILTIN (insb, insb, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (insb64, insb, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (addv2si3, add32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (raddv2si3, radd32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (uraddv2si3, uradd32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kaddv2si3, kadd32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ukaddv2si3, ukadd32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (subv2si3, sub32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (rsubv2si3, rsub32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ursubv2si3, ursub32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ksubv2si3, ksub32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (uksubv2si3, uksub32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (crasv2si, cras32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (crsav2si, crsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (rcrasv2si, rcras32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (rcrsav2si, rcrsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (urcrasv2si, urcras32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (urcrsav2si, urcrsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kcrasv2si, kcras32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kcrsav2si, kcrsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ukcrasv2si, ukcras32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ukcrsav2si, ukcrsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (stasv2si, stas32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (rstasv2si, rstas32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (urstasv2si, urstas32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kstasv2si, kstas32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ukstasv2si, ukstas32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (stsav2si, stsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (rstsav2si, rstsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (urstsav2si, urstsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kstsav2si, kstsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ukstsav2si, ukstsa32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (ashrv2si3, sra32, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (sra32_round, sra32_u, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (lshrv2si3, srl32, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (srl32_round, srl32_u, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (ashlv2si3, sll32, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (ksll32, ksll32, RISCV_UIXLEN_FTYPE_UIXLEN_USI, zprv64),
  RVP_DIRECT_BUILTIN (kslrav2sidi, kslra32, RISCV_UIXLEN_FTYPE_UIXLEN_SI, zprv64),
  RVP_DIRECT_BUILTIN (kslrav2sidi_round, kslra32_u, RISCV_UIXLEN_FTYPE_UIXLEN_SI, zprv64),
  RVP_DIRECT_BUILTIN (sminv2si3, smin32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (uminv2si3, umin32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smaxv2si3, smax32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (umaxv2si3, umax32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kabsv2si2, kabs32, RISCV_UIXLEN_FTYPE_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (khmbb16, khmbb16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (khmbt16, khmbt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (khmtt16, khmtt16, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmbb16, kdmbb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmbt16, kdmbt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmtt16, kdmtt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmabb16, kdmabb16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmabt16, kdmabt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kdmatt16, kdmatt16, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smbb32, smbb32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smbt32, smbt32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smtt32, smtt32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmabb32, kmabb32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmabt32, kmabt32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmatt32, kmatt32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmda32, kmda32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmxda32, kmxda32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmada32, kmada32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmaxda32, kmaxda32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmads32, kmads32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmadrs32, kmadrs32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmaxds32, kmaxds32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmsda32, kmsda32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kmsxda32, kmsxda32, RISCV_IXLEN_FTYPE_IXLEN_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smds32, smds32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smdrs32, smdrs32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (smxds32, smxds32, RISCV_IXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (pkbbv2si, pkbb32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (pkbtv2si, pkbt32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (pktbv2si, pktb32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (pkttv2si, pktt32, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zprv64),
  RVP_DIRECT_BUILTIN (kaddv4qi3, kadd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (kaddv8qi3, kadd8, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN, zpn64),
  RVP_DIRECT_BUILTIN (kaddv4qi3, v_kadd8, RISCV_V4QI_FTYPE_V4QI_V4QI, zpn32),
  RVP_DIRECT_BUILTIN (kaddv8qi3, v64_kadd8, RISCV_V8QI_FTYPE_V8QI_V8QI, zpn64),
  RVP_DIRECT_BUILTIN (rdovsi, rdov, RISCV_UIXLEN_FTYPE_VOID, zpn32),
  RVP_DIRECT_BUILTIN (rdovdi, rdov, RISCV_UIXLEN_FTYPE_VOID, zpn64),
  RVP_DIRECT_BUILTIN (bpicksi, bpick, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn32),
  RVP_DIRECT_BUILTIN (bpickdi, bpick, RISCV_UIXLEN_FTYPE_UIXLEN_UIXLEN_UIXLEN, zpn64),
  RVP_NO_TARGET_BUILTIN (clrovsi, clrov, RISCV_VOID_FTYPE_VOID, zpn32),
  RVP_NO_TARGET_BUILTIN (clrovdi, clrov, RISCV_VOID_FTYPE_VOID, zpn64),
  DIRECT_BUILTIN (frflags, RISCV_USI_FTYPE, hard_float),
  DIRECT_NO_TARGET_BUILTIN (fsflags, RISCV_VOID_FTYPE_USI, hard_float)
};

/* Index I is the function declaration for riscv_builtins[I], or null if the
   function isn't defined on this target.  */
static GTY(()) tree riscv_builtin_decls[ARRAY_SIZE (riscv_builtins)];

/* Get the index I of the function declaration for riscv_builtin_decls[I]
   using the instruction code or return null if not defined for the target.  */
static GTY(()) int riscv_builtin_decl_index[NUM_INSN_CODES];

#define GET_BUILTIN_DECL(CODE) \
  riscv_builtin_decls[riscv_builtin_decl_index[(CODE)]]

/* Return the function type associated with function prototype TYPE.  */

static tree
riscv_build_function_type (enum riscv_function_type type)
{
  static tree types[(int) RISCV_MAX_FTYPE_MAX];

  if (types[(int) type] == NULL_TREE)
    switch (type)
      {
#define DEF_RISCV_FTYPE(NUM, ARGS)					\
  case RISCV_FTYPE_NAME##NUM ARGS:					\
    types[(int) type]							\
      = build_function_type_list (RISCV_FTYPE_ATYPES##NUM ARGS,		\
				  NULL_TREE);				\
    break;
#include "config/riscv/riscv-ftypes.def"
#undef DEF_RISCV_FTYPE
      default:
	gcc_unreachable ();
      }

  return types[(int) type];
}

/* Implement TARGET_INIT_BUILTINS.  */

void
riscv_init_builtins (void)
{

  if (TARGET_64BIT) 
  {
    int_xlen_node  = intDI_type_node;
    uint_xlen_node = unsigned_intDI_type_node;
  } 
    else
  {
    int_xlen_node  = intSI_type_node;
    uint_xlen_node = unsigned_intSI_type_node;
  } 

  for (size_t i = 0; i < ARRAY_SIZE (riscv_builtins); i++)
    {
      const struct riscv_builtin_description *d = &riscv_builtins[i];
      if (d->avail ())
	{
	  tree type = riscv_build_function_type (d->prototype);
	  riscv_builtin_decls[i]
	    = add_builtin_function (d->name, type, i, BUILT_IN_MD, NULL, NULL);
	  riscv_builtin_decl_index[d->icode] = i;
	}
    }
}

/* Implement TARGET_BUILTIN_DECL.  */

tree
riscv_builtin_decl (unsigned int code, bool initialize_p ATTRIBUTE_UNUSED)
{
  if (code >= ARRAY_SIZE (riscv_builtins))
    return error_mark_node;
  return riscv_builtin_decls[code];
}

/* Take argument ARGNO from EXP's argument list and convert it into
   an expand operand.  Store the operand in *OP.  In P extension, it
   helps to make conversions from vectorized mode to constant mode, e.g.
   v8qi to long */

static void
riscv_rvp_prepare_builtin_arg (struct expand_operand *op, tree exp, unsigned argno,
			   enum insn_code icode, bool has_target_p)
{
  enum machine_mode mode = insn_data[icode].operand[argno + has_target_p].mode;
  rtx arg = expand_normal (CALL_EXPR_ARG (exp, argno));
  rtx tmp_rtx = gen_reg_rtx (mode);

  if (!(*insn_data[icode].operand[argno + has_target_p].predicate) (arg, mode))
    {
      if (GET_MODE_SIZE (mode) < GET_MODE_SIZE (GET_MODE (arg)))
	{
	  tmp_rtx = simplify_gen_subreg (mode, arg, GET_MODE (arg), 0);
	  arg = tmp_rtx;
	}
      else if (VECTOR_MODE_P (mode) && CONST_INT_P (arg))
	{
	  /* Handle CONST_INT covert to CONST_VECTOR.  */
	  int nunits = GET_MODE_NUNITS (mode);
	  int i, shift = 0;
    
	  rtvec v = rtvec_alloc (nunits);
	  HOST_WIDE_INT val = INTVAL (arg);
	  enum machine_mode val_mode = GET_MODE_INNER (mode);
	  int shift_acc = GET_MODE_BITSIZE (val_mode);
	  unsigned HOST_WIDE_INT mask = GET_MODE_MASK (val_mode);
	  HOST_WIDE_INT tmp_val = val;
	  for (i = 0; i < nunits; i++)
	    {
	      tmp_val = (val >> shift) & mask;
	      RTVEC_ELT (v, i) = gen_int_mode (tmp_val, val_mode);
	      shift += shift_acc;
	    }

	  arg = copy_to_mode_reg (mode, gen_rtx_CONST_VECTOR (mode, v));
	}
      else
	{
	  convert_move (tmp_rtx, arg, false);
	  arg = tmp_rtx;
	}
    }
  create_input_operand (op, arg, mode);
}

/* Take argument ARGNO from EXP's argument list and convert it into
   an expand operand.  Store the operand in *OP.  */

static void
riscv_prepare_builtin_arg (struct expand_operand *op, tree exp, unsigned argno)
{
  tree arg = CALL_EXPR_ARG (exp, argno);
  create_input_operand (op, expand_normal (arg), TYPE_MODE (TREE_TYPE (arg)));
}

/* Expand instruction ICODE as part of a built-in function sequence.
   Use the first NOPS elements of OPS as the instruction's operands.
   HAS_TARGET_P is true if operand 0 is a target; it is false if the
   instruction has no target.

   Return the target rtx if HAS_TARGET_P, otherwise return const0_rtx.  */

static rtx
riscv_expand_builtin_insn (enum insn_code icode, unsigned int n_ops,
			   struct expand_operand *ops, bool has_target_p)
{
  if (!maybe_expand_insn (icode, n_ops, ops))
    {
      error ("invalid argument to built-in function");
      return has_target_p ? gen_reg_rtx (ops[0].mode) : const0_rtx;
    }

  return has_target_p ? ops[0].value : const0_rtx;
}

/* Expand a RISCV_BUILTIN_DIRECT or RISCV_BUILTIN_DIRECT_NO_TARGET function;
   HAS_TARGET_P says which.  EXP is the CALL_EXPR that calls the function
   and ICODE is the code of the associated .md pattern.  TARGET, if nonnull,
   suggests a good place to put the result.  */

static rtx
riscv_expand_builtin_direct (enum insn_code icode, rtx target, tree exp,
			     bool has_target_p)
{
  struct expand_operand ops[MAX_RECOG_OPERANDS];

  /* Map any target to operand 0.  */
  int opno = 0;
  if (has_target_p)
    create_output_operand (&ops[opno++], target, TYPE_MODE (TREE_TYPE (exp)));

  /* Map the arguments to the other operands.  */
  gcc_assert (opno + call_expr_nargs (exp)
	      == insn_data[icode].n_generator_args);
  for (int argno = 0; argno < call_expr_nargs (exp); argno++){
    if (TARGET_RVP)
      riscv_rvp_prepare_builtin_arg (&ops[opno++], exp, argno, icode, has_target_p);
    else
      riscv_prepare_builtin_arg (&ops[opno++], exp, argno);
  }
  return riscv_expand_builtin_insn (icode, opno, ops, has_target_p);
}

/* Implement TARGET_EXPAND_BUILTIN.  */

rtx
riscv_expand_builtin (tree exp, rtx target, rtx subtarget ATTRIBUTE_UNUSED,
		      machine_mode mode ATTRIBUTE_UNUSED,
		      int ignore ATTRIBUTE_UNUSED)
{
  tree fndecl = TREE_OPERAND (CALL_EXPR_FN (exp), 0);
  unsigned int fcode = DECL_MD_FUNCTION_CODE (fndecl);
  const struct riscv_builtin_description *d = &riscv_builtins[fcode];

  switch (d->builtin_type)
    {
    case RISCV_BUILTIN_DIRECT:
      return riscv_expand_builtin_direct (d->icode, target, exp, true);

    case RISCV_BUILTIN_DIRECT_NO_TARGET:
      return riscv_expand_builtin_direct (d->icode, target, exp, false);
    }

  gcc_unreachable ();
}

/* Implement TARGET_ATOMIC_ASSIGN_EXPAND_FENV.  */

void
riscv_atomic_assign_expand_fenv (tree *hold, tree *clear, tree *update)
{
  if (!TARGET_HARD_FLOAT)
    return;

  tree frflags = GET_BUILTIN_DECL (CODE_FOR_riscv_frflags);
  tree fsflags = GET_BUILTIN_DECL (CODE_FOR_riscv_fsflags);
  tree old_flags = create_tmp_var_raw (RISCV_ATYPE_USI);

  *hold = build4 (TARGET_EXPR, RISCV_ATYPE_USI, old_flags,
		  build_call_expr (frflags, 0), NULL_TREE, NULL_TREE);
  *clear = build_call_expr (fsflags, 1, old_flags);
  *update = NULL_TREE;
}